### ISSUE TITLE
[question] BS power toggling as a user (no sudo)

### ISSUE THREAD

**Issue by panmarco83** [DavidRisch/steamvr_utils#16]
Hello again, this isn't a direct problem and more of a question.
I recently got a Vive Pro since I was suspecting my old Vive was starting to fail (It wasn't, but that's fine).
Now, with the new BS V2(?) they connect and operate in a different way then the V1(?) BS's.
They require that I run this utility as root (sudo) for it to work because of BLE.

I'm wondering if you have any method that would allow the user to be able to toggle the BS's power on and off without needing root (sudo) ?

It's not an actual problem, but more a hindrance to the automation of this script being run on SteamVR startup/shutdown since I now must run the script as root with on/off to power the BS's on/off.

**Comment by DavidRisch** [comment]
https://github.com/DavidRisch/steamvr_utils#install
```bash
sudo setcap 'cap_net_raw,cap_net_admin+eip' /usr/local/lib/python3.?/dist-packages/bluepy/bluepy-helper
```

After running that command you should no longer need root privileges to toggle the basestations over bluetooth. Make sure to pass the version of bluepy you are actually using to that command:

```bash
python3 -c 'import bluepy; print(bluepy.__file__)'
/usr/local/lib/python3.8/dist-packages/bluepy/__init__.py
```

**Comment by panmarco83** [comment]
Ah, okay, I thought I had read the config section completely..
Thank you.

**Comment by panmarco83** [comment]
Thank you, that worked perfectly :)
