### ISSUE TITLE
Audio switching not working with pactl ver 16.1

### ISSUE THREAD

**Issue by Timolsen** [DavidRisch/steamvr_utils#20]
2 script changes are needed for microphone switching to work (it's probably very similar for outputs):

- Change line 25 in 'steamvr_utils/scripts/audio/source_switcher.py' from
from
        return 'move-source-output'
to 
        return 'set-default-source'

- Change line 142 in 'steamvr_utils/scripts/audio/stream_switcher.py'
from
            arguments = ['pactl', self.get_move_stream_connection_command(), str(stream_connection.id), stream.name]
to
            arguments = ['pactl', self.get_move_stream_connection_command(), stream.name]

Have a good one. I'll consider making a code contribution.

**Comment by DavidRisch** [comment]
> Change line 25 in 'steamvr_utils/scripts/audio/source_switcher.py' from
from
return 'move-source-output'
to
return 'set-default-source'

I am pretty sure `set-default-source` and `move-source-output` are two diffrent commands which both exist in older and newer pactrl. Its just a diffrent approch:  `move-source-output` sets the microphone for a specific process and `set-default-source` changes the default every application. I choose to use `move-source-output`, but there are definitly some advantages to `set-default-source`.
If you want to make a PR for your changes please make sure the current behaivour remains as is.  You can add something to the config which defaults to the current implmentation but can also be set to use your proposed change.
